"""Add owner_id and make team_id nullable

Revision ID: 137d5e9a8f95
Revises: 944a15a7686a
Create Date: 2026-10-08 22:16:52.098146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137d5e9a8f95'
down_revision: Union[str, None] = '944a15a7686a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('owner_id', sa.String(), nullable=True))
    op.alter_column('conversations', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.alter_column('conversations', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('conversations', 'owner_id')
    # ### end Alembic commands ###
