"""Add conversation AI config fields

Revision ID: 944a15a7686a
Revises: 832fa9fbc022
Create Date: 2026-10-07 12:34:59.860537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944a15a7686a'
down_revision: Union[str, None] = '832fa9fbc022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum type creation before using it in the column
    executiontarget_enum = sa.Enum('hosted', 'local_runtime', 'team_runtime', name='executiontarget')
    executiontarget_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('conversations', sa.Column('ai_provider', sa.String(), server_default='gemini', nullable=False))
    op.add_column('conversations', sa.Column('ai_model', sa.String(), server_default='gemini-1.5-flash', nullable=False))
    op.add_column('conversations', sa.Column('ai_execution_target', executiontarget_enum, server_default='hosted', nullable=False))
    op.add_column('conversations', sa.Column('ai_system_instructions', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('ai_temperature', sa.Float(), server_default='0.7', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'ai_temperature')
    op.drop_column('conversations', 'ai_system_instructions')
    op.drop_column('conversations', 'ai_execution_target')
    op.drop_column('conversations', 'ai_model')
    op.drop_column('conversations', 'ai_provider')
    # ### end Alembic commands ###
